### ISSUE TITLE
Incorrect relocations

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/llvm2cranelift#2]
For this input:
```llvm
declare void @bar()

define void @call() {
    call void @bar()
    ret void
}
define i64 @address() {
    %t = ptrtoint void ()* @bar to i64
    ret i64 %t
}
```
llvm2cretonne currently produces:
```
$ objdump -drw addr.o

addr.o:     file format elf64-x86-64


Disassembly of section .text.call:

0000000000000000 <call>:
   0:	e8 00 00 00 00       	callq  5 <call+0x5>	1: R_X86_64_PLT32	bar-0x4
   5:	c3                   	retq   

Disassembly of section .text.address:

0000000000000000 <address>:
   0:	48 b8 00 00 00 00 00 00 00 00 	movabs $0x0,%rax	2: R_X86_64_PLT32	bar-0x4
   a:	c3                   	retq   
```
The first issue is that Cretonne is using movabs to compute the function address, which is large-code-model non-PIC, while Faerie is PIC only. This is covered by https://github.com/stoklund/cretonne/issues/188.

The second is that Faerie does not currently have an API for emitting address-of relocations. PIC would want a R_X86_64_GOTPCREL relocation here. This is covered by https://github.com/m4b/faerie/issues/9.

**Comment by jrmuizel** [comment]
Both of the dependent issues have been solved. Is this still an issue?

**Comment by sunfishcode** [comment]
Indeed; this is now fixed. Thanks!
